- name: Add Phalcon PHP Framework PPA repository
  apt_repository: repo='ppa:phalcon/stable'
  tags: pahlcon

- name: Update APT cache
  apt: update_cache=true
  tags: pahlcon

- name: Install Phalcon PHP Framework
  apt: pkg=php5-phalcon state=installed
  tags: pahlcon